M48
; DRILL file {KiCad 7.0.1} date Do 30 Mär 2023 19:37:35 CEST
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2023-03-30T19:37:35+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.1
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.800
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C3.250
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C3.251
%
G90
G05
T1
X47.695Y-153.245
X52.695Y-153.245
T2
X107.415Y-135.462
X107.415Y-148.162
T3
X44.48Y-114.094
X44.48Y-126.794
T0
M30
